// <auto-generated />
using System;
using CRUDAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUDAPI.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20221003222200_criacaoBD")]
    partial class criacaoBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CRUDAPI.Models.Campanha", b =>
                {
                    b.Property<int>("CampanhaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("campanha_id")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DataDeInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_de_inicio");

                    b.Property<DateTime>("DataDeTermino")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_de_termino");

                    b.Property<string>("NomeDaCampanha")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("nome_da_campanha");

                    b.Property<string>("StatusDaCampanha")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status_da_campanha");

                    b.HasKey("CampanhaId");

                    b.ToTable("tb_campanhas");
                });

            modelBuilder.Entity("CRUDAPI.Models.Vacina", b =>
                {
                    b.Property<int>("VacinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vacina_id")
                        .UseIdentityColumn();

                    b.Property<int>("CampanhaId")
                        .HasColumnType("int");

                    b.Property<string>("DicaDaVacina")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dica_da_vacina");

                    b.Property<string>("NomeDaVacina")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_da_vacina");

                    b.HasKey("VacinaId");

                    b.HasIndex("CampanhaId")
                        .IsUnique();

                    b.ToTable("tb_vacinas");
                });

            modelBuilder.Entity("CRUDAPI.Models.Vacina", b =>
                {
                    b.HasOne("CRUDAPI.Models.Campanha", "Campanhas")
                        .WithOne("Vacinas")
                        .HasForeignKey("CRUDAPI.Models.Vacina", "CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanhas");
                });

            modelBuilder.Entity("CRUDAPI.Models.Campanha", b =>
                {
                    b.Navigation("Vacinas");
                });
#pragma warning restore 612, 618
        }
    }
}
